use crate::{
    meta_raster_operator::{
        AutoGenerateDynUnaryCombos, MetaRasterOperator, RasterCreates, RasterWants,
    },
    primitives::Raster,
    source::{CreateUnaryOperator, Query, RasterSource, Source},
};
use num_traits::One;
use serde::{Deserialize, Serialize};
use std::ops::{Add, AddAssign};
use typetag;

/// The NoOp Operator does nothing. It wraps any Operator.
#[derive(Debug, Clone)]
pub struct PlusOneOperator<S> {
    pub source: S,
}

/// It works for anything
impl<T, S> Source for PlusOneOperator<S>
where
    S: Source<Output = Raster<T>>,
    T: AddAssign + Add<T> + One + Copy + Clone + Sized,
{
    type Output = Raster<T>;
    fn query(&self, query: Query) -> Self::Output {
        println!("PlusOneOperator query");
        let mut r = self.source.query(query);
        r.v.iter_mut().for_each(|p| p.add_assign(T::one()));
        r
    }
}

impl<S> CreateUnaryOperator<S, String> for PlusOneOperator<S> {
    fn create<T1>(source: S, _params: String) -> Self {
        PlusOneOperator { source }
    }
}

#[derive(Serialize, Deserialize)]
pub struct MetaPlusOneOperator {
    pub sources: Vec<Box<dyn MetaRasterOperator>>,
}

impl MetaPlusOneOperator {
    pub const REQUIRES_TYPES: [RasterWants; 1] = [RasterWants::Any];
}

#[typetag::serde]
impl MetaRasterOperator for MetaPlusOneOperator {
    fn creates_type(&self) -> RasterCreates {
        self.sources[0].creates_type()
    }
    fn requires_type(&self) -> &[RasterWants] {
        &MetaPlusOneOperator::REQUIRES_TYPES
    }

    fn create_u8_raster_op(&self) -> Box<dyn RasterSource<RasterType = u8>> {
        self.auto_create_u8_raster_op::<PlusOneOperator<Box<dyn RasterSource<RasterType = _>>>>()
    }
    fn create_u16_raster_op(&self) -> Box<dyn RasterSource<RasterType = u16>> {
        self.auto_create_u16_raster_op::<PlusOneOperator<Box<dyn RasterSource<RasterType = _>>>>()
    }
    fn raster_sources(&self) -> &[Box<dyn MetaRasterOperator>] {
        self.sources.as_slice()
    }
}

impl AutoGenerateDynUnaryCombos for MetaPlusOneOperator {}
